services:
  runner:
    image: landscapedatacommons/actions-runner:1.0.1
    restart: always
    environment:
      REPO: /run/secrets/repo 
      TOKEN: /run/secrets/token
    secrets:
      - repo
      - token
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: replicated 
      replicas: 3
      #
      resources:
        limits: 
          cpus: '0.35'
          memory: 300M
        reservations:
          cpus: '0.25'
          memory: 128M
secrets:
  repo:
    file: repo.txt 
  token:
    file: token.txt
      