services:
  runner:
    image: landscapedatacommons/jornada-runner:1.0.4
    build:
      dockerfile: Dockerfile
      context: .
      secrets:
        - repo
        - token
    # restart: always
    secrets:
        - repo
        - token
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - docker_sock_vol:/var/run
    
    deploy:
      mode: replicated 
      replicas: 3
      resources:
        limits: 
          cpus: '0.35'
          memory: 300M
        reservations:
          cpus: '0.25'
          memory: 128M

# usable socket that is not the host machine
  sidecar:
    image: docker:dind
    command: []
    depends_on:
      - runner
    privileged: true
    volumes:
      - docker_sock_vol:/var/run 
volumes:
  docker_sock_vol:

secrets:
  repo:
    file: ./repo.txt 
    # external: true
  token:
    file: ./token.txt
    # external: true
      