services:
  runner:
    image: landscapedatacommons/jornada-runner-ldc:1.0.0
    build:
      dockerfile: ldc.Dockerfile
      context: .
    logging:
      driver: "json-file"
      options:
        max-file: 3
        max-size: 10m
    restart: always
    environment:
      - DOCKER_HOST=tcp://sidecar:2376
      - TARGETREPO=Landscape-Data-Commons
      - DOCKER_TLS_VERIFY=1
      - DOCKER_CERT_PATH=/certs/client
      # - TOKEN=/run/secrets/ldc_pat
    secrets:
      - source: ldc_pat
        target: ldc_pat
        uid: '1001'  
        gid: '1001'
        mode: 0400
    volumes:
      - certs:/certs:ro

    #volumes:
      # - actions-runner_sidecar_sock_vol:/var/run/
     # - dind-certs-client:/certs/client:ro
    
    deploy:
      mode: replicated 
      replicas: 3
      resources:
        limits: 
          cpus: '0.35'
          memory: 300M
        reservations:
          cpus: '0.25'
          memory: 128M

    networks:
     - runner-network
 
secrets:
  ldc_pat:
    external: true
volumes:
  certs:
    name: runner-certs
    external: true
  
  # file: ./ldc_pat.txt
#volumes:
  # actions-runner_sidecar_sock_vol:
  #   external: true
  #   name: actions-runner_sidecar_sock_vol
  #dind-certs-client:
   # external: true
networks:
  runner-network:
    name: runner-network
    external: true
