
services:
  sidecar:
    user: root
    # image: docker:dind-rootless
    image: landscapedatacommons/jornada-dind:1.0.0
    build:
      dockerfile: dind.Dockerfile
      context: .
    logging:
      driver: "json-file"
      options:
        max-file: 3
        max-size: 10m
    init: true
    entrypoint: "/usr/local/bin/entrypoint.sh"
    privileged: true
    restart: always
    environment:
      - DOCKER_TLS_CERTDIR=/certs
      - DOCKER_TLS_VERIFY=1
      - DOCKER_CERT_PATH=/certs/client
    volumes:
      - certs:/certs
      #- DOCKER_DAEMON_ARGS="--tls=false --host=tcp://0.0.0.0:2375"


    #volumes:

     # - dind-certs-client:/certs/client
    networks:
      - runner-network
    # network_mode: "host"
#volumes:
  # actions-runner_sidecar_sock_vol:
  #   external: true
  #dind-certs-ca:
    # external: true
  #dind-certs-client:
    # external: true
volumes:
  certs:
    name: runner-certs
    
networks:
  runner-network:
    name: runner-network
    external: true
